apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: {{ .Values.headless.port }}
      targetPort: 6379
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
